-- V1__init_schema.sql
-- Initial database schema generated from Hibernate

-- ============================================================
--  TABLE CREATION
-- ============================================================

CREATE TABLE user_snapshot (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   full_name varchar(255) NOT NULL,
   email VARCHAR(255) NOT NULL,
   phone_number VARCHAR(20),
   external_user_id BIGINT NOT NULL UNIQUE,
   last_updated TIMESTAMP(6) NOT NULL,
   roles JSONB NOT NULL DEFAULT '[]'
);

CREATE TABLE medical_record (
    record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_code UUID NOT NULL UNIQUE,
    patient_id BIGINT,
    assigned_user BIGINT,
    created_by BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'EMPTY'
        CHECK (status IN ('EMPTY', 'PUBLISHED', 'COMPLETED', 'ACTIVE', 'INACTIVE', 'DELETED', 'HIDDEN')),
    updated_by BIGINT,
    visit_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE clinical_note (
   note_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   record_id BIGINT NOT NULL,
   noted_by BIGINT NOT NULL,
   note TEXT NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ============================================================
--  INDEXES
-- ============================================================

CREATE INDEX IF NOT EXISTS medical_record_patient_id_index
    ON medical_record (patient_id);

CREATE INDEX IF NOT EXISTS clinical_note_record_id_index
    ON clinical_note (record_id);

-- ============================================================
--  FOREIGN KEYS
-- ============================================================

ALTER TABLE medical_record
    ADD CONSTRAINT fk_medical_record_assigned_user
        FOREIGN KEY (assigned_user) REFERENCES user_snapshot (external_user_id);

ALTER TABLE medical_record
    ADD CONSTRAINT fk_medical_record_created_by
        FOREIGN KEY (created_by) REFERENCES user_snapshot (external_user_id);

ALTER TABLE medical_record
    ADD CONSTRAINT fk_medical_record_updated_by
        FOREIGN KEY (updated_by) REFERENCES user_snapshot (external_user_id);

ALTER TABLE medical_record
    ADD CONSTRAINT fk_medical_record_patient
        FOREIGN KEY (patient_id) REFERENCES user_snapshot (external_user_id);

ALTER TABLE clinical_note
    ADD CONSTRAINT fk_clinical_note_record
        FOREIGN KEY (record_id) REFERENCES medical_record (record_id);

ALTER TABLE clinical_note
    ADD CONSTRAINT fk_clinical_note_noted_by
        FOREIGN KEY (noted_by) REFERENCES user_snapshot (external_user_id);
