services:
  # --------------------------------- Kafka(all services) -----------------------------------#
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"      # for localhost
      - "29092:29092"    # for other docker containers
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      CLUSTER_ID: MkQkDjFzNTcwNTJENDM2Qk
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - app-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "7070:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    restart: unless-stopped
    networks:
      - app-network

  #------------------------------ Postgres (testorder:5434) ---------------------#
  postgres-testorder-service:
    image: postgres:15.5
    container_name: postgres_test_order_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: testorder_db
    ports:
      - "5434:5432"
    volumes:
      - test_order_volume:/var/lib/postgresql/data

#--------------------------------- MongoDB (testorder - 27018) --------------------#
  mongodb_audit_service:
    image: mongo:7.0.5
    container_name: mongodb_audit_service_container
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: medicalAuditDb
    volumes:
      - medicalAuditVolume:/data/db
    networks:
      medical_audit_mongo_network:

#---------------------------------- # Postgres (testorder: 5433) ----------------------#
  postgres-patient-service:
    image: postgres:15.5
    container_name: postgres_patient_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: patientdb
    ports:
      - "5433:5432"
    volumes:
      - patient_volume:/var/lib/postgresql/data

#--------------------------------- # Elastic-search (patient: 9200) ------------------------------------#
  patient-elasticsearch-service:
    container_name: patient-elasticsearch-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - patient-elasticsearch-net
    ports:
      - 9200:9200
    volumes:
      - patient-elasticsearch-data:/usr/share/elasticsearch/data

# ------------------------------------------ postgres (payment: 5435) --------------------#
  postgres-payment-service:
    image: postgres:15.5
    container_name: postgres_payment_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: paymentdb
    ports:
      - "5435:5432"
    volumes:
      - payment_volume:/var/lib/postgresql/data
    networks:
      - payment-network

  # ------------------------------------------ Redis (payment: 6379) --------------------#
  redis-payment-service:
    image: redis:7-alpine
    container_name: redis_payment_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_payment_volume:/data
    networks:
      - payment-network

  #------------------------------------------- Mongodb (instrument: 27017) --------------#
  monitoring-service-db:
    image: mongo:7.0.5
    container_name: monitoring-service-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
      - MONGO_INITDB_DATABASE=monitoring_db
    ports:
      - "27017:27017"
    networks:
      - internal

networks:
  app-network:
    driver: bridge
  medical_audit_mongo_network:
  patient-elasticsearch-net:
  payment-network:
  internal:

volumes:
  test_order_volume:
  medicalAuditVolume:
  patient_volume:
  patient-elasticsearch-data:
  payment_volume:
  redis_payment_volume: