spring.application.name=api-gateway
server.port=9000
spring.profiles.active=routing-webflux,cors
management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.enable.http.server.requests=true