
app:
  name: api-gateway
  api-version: /api/v1

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # for IAM service
            - id: iam-service
              uri: http://localhost:8080
              predicates:
                - Path=${app.api-version}/iam/**
              filters:
                - RewritePath=/iam/(?<segment>(\\d+|auth|roles|logs|users.*)), /${segment}
                - RewritePath=/api/v1/iam/(?<segment>(\\d+|auth|roles|logs|users.*)), /api/v1/${segment}


            # for instrument service
            - id: instrument-service
              uri: http://localhost:8081
              predicates:
                - Path=${app.api-version}/instruments/**
              filters:
                - RewritePath=/api/v1/patients/(?<segment>(\\d+|blood-testing|reagents|instruments.*)), /api/v1/${segment}


            # for monitoring service
            - id: monitoring-service
              uri: http://localhost:8083
              predicates:
                - Path=${app.api-version}/monitoring/**
              filters:
                - RewritePath=/api/v1/monitoring/(?<segment>.*), /api/v1/${segment}

            # for patient service
            - id: patient-service
              uri: http://localhost:8087
              predicates:
                - Path=${app.api-version}/patients/**
              filters:
                - RewritePath=/api/v1/patients/(?<segment>(\\d+|audit-entries|clinical-notes|medical-records|user-snapshots.*)), /api/v1/${segment}

            # for payment service
            - id: payment-service
              uri: http://localhost:8084
              predicates:
                - Path=${app.api-version}/payments/**
              filters:
                - RewritePath=/api/v1/payments/(?<segment>(\\d+|payment-providers|paypal|payments/stripe|payments/vnpay.*)), /api/v1/${segment}

            # for test order service
            - id: testorder-service
              uri: http://localhost:8085
              predicates:
                - Path=/api/v1/test-orders/**       # everything under test-orders
              filters:
                - RewritePath=/api/v1/test-orders/(?<segment>(\\d+|parameters|test-result.*)), /api/v1/${segment}

            # for warehouse service
            - id: warehouse-service
              uri: http://localhost:8086
              predicates:
                - Path=${app.api-version}/warehouses/**,
              filters:
                - RewritePath=/api/v1/warehouses/(?<segment>(\\d+|instruments|vendors|configurations|reagents|supply|usage.*)), /api/v1/${segment}