app:
  cors:
    allowed-origins:
      - http://localhost:5173
      - http://ec2-100-27-242-198.compute-1.amazonaws.com:5173
      # - https://your-production-domain.com
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
    allowed-headers:
      - "*"
    allow-credentials: true
    max-age: 3600
