global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'job']
  group_wait: 10s
  group_interval: 10m
  repeat_interval: 1h
  receiver: 'telegram-receiver'

receivers:
  - name: 'telegram-receiver'
    telegram_configs:
      - bot_token: "8145943729:AAHJnNkpEBBgNdiU3nNaDbosqq9TNHVTlY4"
        chat_id: -4821904329
        message: >-
          🚨 *{{ .CommonAnnotations.summary }}*
          
          {{ .CommonAnnotations.description }}
          
          *Alert Details:*
          • *Alert Type:* {{ .CommonLabels.alertname }}
          • *Service:* {{ .CommonLabels.job }}
          {{ if .CommonLabels.uri }}• *Endpoint:* {{ .CommonLabels.uri }}{{ end }}
          {{ if .CommonLabels.status }}• *Status Code:* {{ .CommonLabels.status }}{{ end }}
          • *Severity:* {{ index .CommonLabels "severity" }}
          • *Timestamp:* {{ .Alerts.Firing | len }} firing
        parse_mode: "Markdown"

