package sum25.group03.testorderservice.enums;

public enum ActionTypeFeatures {
    // test orders
    CREATE_TEST_ORDER,
    VIEW_TEST_ORDER_LIST,
    VIEW_TEST_ORDER_DETAIL,
    UPDATE_TEST_ORDER_STATUS,
    UPDATE_TEST_ORDER_INFO,
    DELETE_TEST_ORDER,

    // test results
    CREATE_BULK_TEST_RESULTS,
    VIEW_TEST_RESULT_LIST,
    VIEW_TEST_RESULT_DETAIL,
    UPDATE_TEST_RESULT,
    DELETE_TEST_RESULT,
    REVIEW_TEST_RESULT
}
