package sum25.group03.patientservice.enums;

public enum ActionTypeFeatures {
    // patient:
    CREATE_NEW_PATIENT_MEDICAL_RECORD,
    VIEW_PATIENT_MEDICAL_RECORD_DETAIL,
    VIEW_ALL_PATIENT_MEDICAL_RECORDS,
    DELETE_PATIENT_MEDICAL_RECORD,
    UPDATE_ASSIGNED_DOCTOR_DETAIL,
    UPDATE_MEDICAL_RECORD_STATUS,
    UPDATE_PATIENT_MEDICAL_RECORD_STATUS,

    // audit:
    VIEW_AUDIT_LOGS,
    AUDIT_MEDICAL_RECORD_STATUS_CHANGE
}
