server:
  port: 8081
  error:
    include-stacktrace: never
    include-message: always
spring:
  application:
    name: instrument-service
  profiles:
    active: @spring.profiles.active@
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    consumer:
      group-id: instrument-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    web: info
    root: info
    io.grpc: info

grpc:
  warehouse:
    host: localhost
    port: 9002
  testorder:
    host: localhost
    port: 9001

aws:
#  region: ap-southeast-1
#  access-key-id: ${AWS_ACCESS_KEY_ID}
#  secret-key-secret: ${AWS_SECRET_ACCESS_KEY}
  region: ap-southeast-1
  access-key-id: AKIA3RDIYFHPZTTDJPN3
  secret-key-secret: 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
#  AWS_ACCESS_KEY_ID=AKIA3RDIYFHPZTTDJPN3;AWS_SECRET_ACCESS_KEY=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
audit:
  cloudwatch:
    log-group: Instrument-service
    enabled: true
