
# for paypal gateway:
payment:
  paypal:
    client-id: ${PAYPAL_CLIENT_ID}
    client-secret: ${PAYPAL_CLIENT_SECRET}
    mode: sandbox
    api:
      base-url: https://api-m.sandbox.paypal.com
  redis:
    ttl: 1800

# for stripe gateway:
stripe:
  secret-key: sk_test_51SMkxFDAubI9QHGxdhUqNxFl4l2GMGmzBkkloDIhXWmoOieSq673SmO8lu6kvtsfqB1i6isItbUNC5bzL1sI2N0s002yvVcO3H
  web-hook-secret: whsec_3486cac37e172ecebbdad8122dc66487345755a6cd8b8616cba2b2c3ab335dcc

# for vnpay gateway:
vnpay:
  tmn-code: "${VNP_TMN_CODE}"
  hash-secret: "${VNP_HASH_SECRET}"
  payment-url: '${VNP_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}'
  query-url: "${VNP_QUERY_URL:https://sandbox.vnpayment.vn/merchant_webapi/api/transaction}"
  refund-url: "${VNP_REFUND_URL:https://sandbox.vnpayment.vn/merchant_webapi/api/refund}"
  return-url: "${VNP_RETURN_URL:http://localhost:8080/api/v1/payment/vnpay/return}"
  ipn-url: "${VNP_IPN_URL}"
  version: "2.1.0"
  command: "pay"
  order-type: "other"
  locale: "vn"
  qr-code:
    enabled: true
    default-width: 300
    default-height: 300
