
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: payment-service-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "sum25.group03.common.response.events"
        spring.json.use.type.headers: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      # Keep type headers so consumers can deserialize by class
      properties:
        spring.json.add.type.headers: true