vnpay:
  tmn-code: "${VNP_TMN_CODE}"
  hash-secret: "${VNP_HASH_SECRET}"
  payment-url: '${VNP_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}'
  query-url: "${VNP_QUERY_URL:https://sandbox.vnpayment.vn/merchant_webapi/api/transaction}"
  refund-url: "${VNP_REFUND_URL:https://sandbox.vnpayment.vn/merchant_webapi/api/refund}"
  return-url: "${VNP_RETURN_URL:http://localhost:8080/api/v1/payment/vnpay/return}"
  ipn-url: "${VNP_IPN_URL}"
  version: "2.1.0"
  command: "pay"
  order-type: "other"
  locale: "vn"
  qr-code:
    enabled: true
    default-width: 300
    default-height: 300
