
spring:
  datasource:
#    KHANH:
#    url: ${PATIENT_DB_URL:jdbc:postgresql://localhost:5432/testorder_db}
#    username: ${PATIENT_DB_USERNAME:postgres}
#    password: ${PATIENT_DB_PASSWORD:123456}

#    ORIGIN:
#    url: ${PATIENT_DB_URL:jdbc:postgresql://localhost:5434/testorder_db}
#    username: ${PATIENT_DB_USERNAME:postgres}
#    password: ${PATIENT_DB_PASSWORD:12345}

    # Tri's postgres
    url: jdbc:postgresql://pg-11205524-quachtri865-70aa.c.aivencloud.com:22441/defaultdb?sslmode=require
    username: avnadmin
    password: AVNS_OueYmZUJ75GK00khbkn
    driver-class-name: org.postgresql.Driver

    hikari:
      pool-name: PatientHikariCP
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: "SELECT 1"

  jpa:
    hibernate:
      ddl-auto: none # change to 'update' or 'none' if you prefer different behavior
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: true
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: [health, info,prometheus]
  health:
    db:
      enabled: true
