spring:
  profiles:
    active: testorderdb
  kafka:
    listener:
      ack-mode: manual
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-order-result
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

corehere:
  client-name: default
  api-key: yNWIxRbIiAEGo7MsgioKEQejCfUZ0vU0TgKgMHgA