spring.application.name=monitoring-service


spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer


server.port=4000
logging.level.root=info

monitoring.kafka.topic=processed-test-results
monitoring.kafka.raw-topic=raw-test-results
spring.retry.enabled=true