server:
  port: 8083

spring:
  application:
    name: monitoring-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: monitoring-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
        enable.auto.commit: false
        max.poll.records: 100
      listener:
        ack-mode: manual
        concurrency: 3

  data:
    mongodb:
      uri: mongodb+srv://admin:12345@monitoring.lop4zd8.mongodb.net/monitoring?retryWrites=true&w=majority
#      uri: mongodb://root:root123@localhost:27017/monitoring_db?authSource=admin

  retry:
    enabled: true

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      tags:
        application: monitoring-service
      export:
        enabled: true


monitoring:
  kafka:
    topics:
      - monitoring-log
