-- =========================================================
-- Flyway Migration: Initial schema for TestOrder Service
-- Generated from Hibernate DDL (converted for PostgreSQL)
-- =========================================================

-- Drop existing tables if they exist (safe reset for dev)
-- DROP TABLE IF EXISTS comment CASCADE;
-- DROP TABLE IF EXISTS parameters CASCADE;
-- DROP TABLE IF EXISTS reagent_used CASCADE;
-- DROP TABLE IF EXISTS synced_configurations CASCADE;
-- DROP TABLE IF EXISTS test_order.proto CASCADE;
-- DROP TABLE IF EXISTS test_result CASCADE;
-- DROP TABLE IF EXISTS test_result_reagent_used CASCADE;

-- =========================================================
-- Table: comment
-- =========================================================
CREATE TABLE comment (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         created_at TIMESTAMP(6) NOT NULL,
                         updated_at TIMESTAMP(6) NOT NULL,
                         updatedBy BIGINT,
                         user_id BIGINT NOT NULL,
                         test_order_id BIGINT,
                         test_result_id BIGINT,
                         comment_text TEXT NOT NULL,
                         status VARCHAR(255) CHECK (status IN ('VISIBLE','HIDDEN','DELETED', 'ACTIVE'))
);

-- =========================================================
-- Table: parameters
-- =========================================================
CREATE TABLE parameters (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            external_id BIGINT NOT NULL,
                            created_at DATE NOT NULL,
                            updated_at DATE NOT NULL,
                            createdBy BIGINT,
                            updatedBy BIGINT,
                            name VARCHAR(255) NOT NULL,
                            param_code VARCHAR(255) NOT NULL,
                            abbreviation VARCHAR(255),
                            description VARCHAR(255),
                            min DOUBLE PRECISION,
                            max DOUBLE PRECISION,
                            gender VARCHAR(255) CHECK (gender IN ('FEMALE', 'MALE', 'BOTH')),
                            status VARCHAR(255) CHECK (status IN ('ACTIVE','INACTIVE','DEPRECATED','DELETED')),
                            unit VARCHAR(255) CHECK (unit IN (
                                                              'PERCENTAGE','CELSIUS','BPM','CELLS_PER_UL','MILLIONS_PER_UL','FL','PG','G_PER_DL'
                                )),
                            price BIGINT NOT NULL,
                            CONSTRAINT unique_param_code_per_gender UNIQUE (param_code, gender)
);

-- =========================================================
-- Table: synced_configurations
-- =========================================================
CREATE TABLE synced_configurations (
                                       id BIGINT NOT NULL PRIMARY KEY,
                                       minValue DOUBLE PRECISION,
                                       maxValue DOUBLE PRECISION,
                                       syncedAt TIMESTAMP(6),
                                       configKey VARCHAR(255),
                                       description VARCHAR(255),
                                       status VARCHAR(255) CHECK (status IN ('ACTIVE','INACTIVE','PENDING','DEPRECATED','DELETED')),
                                       unit VARCHAR(255)
);

-- =========================================================
-- Table: test_order.proto
-- =========================================================
CREATE TABLE test_order (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            code uuid  NOT NULL UNIQUE,
                            type VARCHAR(255) CHECK (type IN (
                                  'CBC_TEST','DIABETES_TEST'
                            )),
                            barcode VARCHAR(255) UNIQUE,
                            run_date DATE,
                            global_test_parameter_id BIGINT,
                            created_at TIMESTAMP(6) NOT NULL,
                            updated_at TIMESTAMP(6) NOT NULL,
                            created_by BIGINT NOT NULL,
                            external_medical_record_id BIGINT NOT NULL,
                            patient_id BIGINT,
                            run_by BIGINT,
                            instrument_id BIGINT,
                            status VARCHAR(255) CHECK (status IN (
                                                                  'EMPTY', 'UNPUBLISHED','UNASSIGNED','PENDING','ONGOING','WAITING', 'FAILED', 'CANCELED','COMPLETED','REVIEWED','AI_REVIEWED', 'WAITING_PAYMENT'
                                ))
);

-- =========================================================
-- Table: test_result
-- =========================================================
CREATE TABLE test_result (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             value DOUBLE PRECISION,
                             configuration_id BIGINT,
                             instrument_id BIGINT,
                             parameter_id BIGINT NOT NULL,
                             test_order_id BIGINT NOT NULL,
                             created_at TIMESTAMP(6) NOT NULL,
                             updated_at TIMESTAMP(6) NOT NULL,
                             flag_status VARCHAR(255),
                             status VARCHAR(255) NOT NULL CHECK (status IN (
                                                                            'PENDING','COMPLETED','FAILED','CANCELLED','WAITING','REVIEWED','AI_REVIEWED'
                                 )),
                             CONSTRAINT unique_testorder_parameter UNIQUE (test_order_id, parameter_id)
);


-- =========================================================
-- Foreign Keys
-- =========================================================
ALTER TABLE comment
    ADD CONSTRAINT FKrhj2aekh7aftu5lbc36lue7he
        FOREIGN KEY (test_order_id) REFERENCES test_order(id);

ALTER TABLE comment
    ADD CONSTRAINT FKlaw9vmjhkmgktasyq5qnurc2u
        FOREIGN KEY (test_result_id) REFERENCES test_result(id);

ALTER TABLE test_result
    ADD CONSTRAINT FKketyjqymc5etacxoxpeqykx1o
        FOREIGN KEY (parameter_id) REFERENCES parameters(id);

ALTER TABLE test_result
    ADD CONSTRAINT FK8xu41vv64hcofgotrkqayhx3y
        FOREIGN KEY (configuration_id) REFERENCES synced_configurations(id);

ALTER TABLE test_result
    ADD CONSTRAINT FKrgqm2iyxs1kweaditl2nd2hhn
        FOREIGN KEY (test_order_id) REFERENCES test_order(id);

-- ===========================================================
-- indexes
-- ===========================================================
-- Index for "first per external_id" queries
CREATE INDEX idx_parameters_external_id_id
    ON parameters (external_id, id);