
version: '4'
services:
  postgres-patient-service:
    image: postgres:15.5
    container_name: postgres_patient_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: patientdb
    ports:
      - "5433:5432"
    volumes:
      - patient_volume:/var/lib/postgresql/data
volumes:
  patient_volume:
