version: '4'
services:
  mongodb_audit_service:
    image: mongo:7.0.5
    container_name: mongodb_audit_service_container
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: medicalAuditDb
    volumes:
      - medicalAuditVolume:/data/db
    networks:
      medical_audit_mongo_network:

volumes:
  medicalAuditVolume:

networks:
  medical_audit_mongo_network: