
spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      database: audit-service
      username: root
      password: 12345
      authentication-database: admin
# spring.data.mongodb.uri=mongodb://root:12345@localhost:27017/product-service?authSource=admin - application.properties