# ==========================
# APP CONFIG
# ==========================
spring.application.name=iam-service
server.port=8080

# ==========================
# DATABASE (PostgreSQL on AWS RDS)
# ==========================
spring.datasource.url=jdbc:postgresql://iam.cjguysc2gq58.ap-southeast-2.rds.amazonaws.com:5432/postgres
spring.datasource.username=yoko
spring.datasource.password=hoang229
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ? Timezone fix (Asia/Saigon is invalid)
spring.datasource.hikari.data-source-properties.serverTimezone=Asia/Ho_Chi_Minh
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh

# ==========================
# KAFKA CONFIG
# ==========================
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID:iam-service-group}

# Kafka producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=true

spring.kafka.consumer.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Kafka consumer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# Trust only shared event package
spring.kafka.consumer.properties.spring.json.trusted.packages=sum25.group03.common.response.events
# Use headers to know the target class
spring.kafka.consumer.properties.spring.json.use.type.headers=true

# ==========================
# LOGGING
# ==========================
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true

