spring.application.name=iam-service
spring.datasource.url=jdbc:postgresql://iam.cjguysc2gq58.ap-southeast-2.rds.amazonaws.com:5432/postgres
spring.datasource.username=yoko
spring.datasource.password=hoang229
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
